#!/bin/bash 

if [[ $# -eq 0 ]]
then  
    echo "provide sum input"
    exit 1
fi

if [[ $(id -u) -ne 0 ]]
then 
     echo "user not root user and dont have sudo privillage"
     exit 2
fi 

for each in "$@" 
do 
  if which $each >> /root/file12.txt 2>/dev/null
 then 
     echo "${each}_this package is alredy installed"
else 
     echo "installing $each"
     yum install ${each} -y >> /root/file12.txt
     if [[ $? -eq 0 ]]
     then
       echo "success or install is success"
     fi  
  fi
done
